# Generated by Django 4.1.5 on 2023-02-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0003_alter_blogpost_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Description5',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Title1',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Title14',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Title2',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Title3',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
