# Generated by Django 4.1.5 on 2023-02-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0007_remove_blogpost_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Sluglink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
