# Generated by Django 3.2.23 on 2024-05-21 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0012_auto_20240521_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 14, 10, 32, 539757)),
        ),
        migrations.AlterField(
            model_name='media',
            name='Slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
