# Generated by Django 3.2.23 on 2024-05-21 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0013_auto_20240521_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 15, 32, 28, 968792)),
        ),
    ]
