# Generated by Django 3.2.23 on 2024-05-21 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0014_auto_20240521_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='url',
            new_name='Url',
        ),
        migrations.AddField(
            model_name='media',
            name='CreatedAt',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='media',
            name='CreatedPaperName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 16, 6, 13, 659717)),
        ),
    ]
