# Generated by Django 3.2.23 on 2024-05-21 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0015_auto_20240521_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 17, 3, 2, 49274)),
        ),
        migrations.AlterField(
            model_name='media',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='media',
            name='Title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='media',
            name='Url',
            field=models.URLField(default='', max_length=300, null=True),
        ),
    ]
