# Generated by Django 5.0.6 on 2024-06-08 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0019_getstartedform_alter_contactdata_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Getstartedform',
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 8, 9, 19, 16, 472335)),
        ),
    ]
