# Generated by Django 5.0.6 on 2024-06-09 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0020_delete_getstartedform_alter_contactdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepformData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brandmarketposition', models.CharField(max_length=100)),
                ('BrandCorevalue', models.CharField(max_length=500)),
                ('Brandperceive_targetaudience', models.CharField(max_length=100)),
                ('CustomerFeedback', models.CharField(max_length=100)),
                ('BrandPerformence', models.CharField(max_length=500)),
                ('Challenges_Obstacles', models.CharField(max_length=500)),
                ('Brand_Motivation', models.CharField(max_length=100)),
                ('Goals_Achieves', models.CharField(max_length=500)),
                ('Expectations', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 17, 4, 53, 426264)),
        ),
    ]
