# Generated by Django 5.0.6 on 2024-06-09 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0021_stepformdata_alter_contactdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepformdata',
            name='Email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stepformdata',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stepformdata',
            name='Phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 17, 52, 40, 635549)),
        ),
    ]
