# Generated by Django 5.0.6 on 2024-06-09 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0023_alter_contactdata_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 9, 20, 43, 10, 237562)),
        ),
        migrations.AlterField(
            model_name='stepformdata',
            name='Email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
