# Generated by Django 5.0.6 on 2024-06-28 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0026_applyform_active_status_alter_contactdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='Active_status',
            field=models.IntegerField(choices=[(0, 'activate'), (1, 'inactivate')], default=1),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 0, 55, 37, 64299)),
        ),
    ]
