# Generated by Django 5.0.6 on 2024-06-28 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0027_alter_applyform_active_status_alter_contactdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 0, 57, 25, 754999)),
        ),
    ]
