# Generated by Django 5.0.6 on 2024-07-02 18:58

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0030_workpost_alter_contactdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('CreatedAt', models.DateField(default=datetime.datetime.now)),
                ('JobType', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('Body', ckeditor.fields.RichTextField()),
                ('Experience', models.CharField(max_length=50)),
                ('WorkingHours', models.CharField(max_length=100)),
                ('WorkingDays', models.CharField(max_length=50)),
                ('Salary', models.CharField(max_length=50)),
                ('Vacancy', models.IntegerField(default='')),
                ('DeadLine', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 0, 28, 54, 924149)),
        ),
    ]
