# Generated by Django 5.0.6 on 2024-07-02 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0032_alter_contactdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerinfo',
            name='Sluglink',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 0, 36, 46, 128315)),
        ),
    ]
