# Generated by Django 5.0.6 on 2024-07-02 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0033_careerinfo_sluglink_alter_contactdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyform',
            name='Active_status',
        ),
        migrations.AddField(
            model_name='careerinfo',
            name='Active_status',
            field=models.IntegerField(choices=[(0, 'active'), (1, 'inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 0, 48, 53, 988198)),
        ),
    ]
