# Generated by Django 5.0.6 on 2024-07-03 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0035_rename_jobtitle_careerinfo_expertisename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 16, 29, 7, 603808)),
        ),
    ]
