# Generated by Django 5.0.6 on 2024-07-03 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0039_alter_contactdata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='careerinfo',
            name='ExpertiseId',
            field=models.IntegerField(default=0, serialize=False),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 16, 48, 8, 139553)),
        ),
    ]
