# Generated by Django 5.0.6 on 2024-07-05 11:12

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0040_remove_careerinfo_id_careerinfo_expertiseid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpost',
            name='Body',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='workpost',
            name='CreateAt',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='workpost',
            name='CreateName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workpost',
            name='Slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='careerinfo',
            name='ExpertiseId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 5, 16, 42, 25, 398676)),
        ),
        migrations.AlterField(
            model_name='workpost',
            name='Title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
