# Generated by Django 4.1.5 on 2023-02-11 07:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0006_alter_blogpost_description1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='Description1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='Description2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='Description3',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='Description4',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='Description5',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='Title1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='Title14',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='Title2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='Title3',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='Body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
