# Generated by Django 4.1.5 on 2023-02-17 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0009_contact_remove_blogpost_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=500)),
                ('Date', models.DateTimeField(default=datetime.datetime(2023, 2, 17, 16, 48, 42, 103112))),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
