# Generated by Django 3.2.23 on 2024-05-21 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0011_alter_contactdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Slug', models.SlugField()),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 13, 58, 1, 861098)),
        ),
    ]
