# Generated by Django 3.2.23 on 2024-05-21 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0017_auto_20240521_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 17, 15, 21, 284093)),
        ),
        migrations.AlterField(
            model_name='media',
            name='CreatedAt',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
