# Generated by Django 5.0.6 on 2024-06-28 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0025_applyform_alter_contactdata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyform',
            name='Active_status',
            field=models.IntegerField(choices=[('inactive', 'inactive'), ('active', 'active')], default='inactive'),
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 0, 51, 30, 736940)),
        ),
    ]
