# Generated by Django 5.0.6 on 2024-07-03 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magsmenapp', '0034_remove_applyform_active_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerinfo',
            old_name='JobTitle',
            new_name='ExpertiseName',
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 16, 21, 47, 158465)),
        ),
    ]
